# Generated by Django 3.2.3 on 2021-05-16 09:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(max_length=150, verbose_name='Loan Type')),
                ('percentage', models.IntegerField(verbose_name='Percentage')),
            ],
            options={
                'verbose_name': 'Loans',
                'verbose_name_plural': 'Loanss',
                'db_table': 'loan_types',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('headline', models.CharField(max_length=550, verbose_name='Headline')),
                ('body', models.TextField(max_length=150, verbose_name='Loan Type')),
                ('new_image', models.ImageField(upload_to='img_uploads/')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
                'db_table': 'news',
            },
        ),
    ]
